var annotated =
[
    [ "AVLTree", "class_a_v_l_tree.html", "class_a_v_l_tree" ],
    [ "AVLTreeNode", "class_a_v_l_tree_node.html", "class_a_v_l_tree_node" ],
    [ "HeapSorter", "class_heap_sorter.html", "class_heap_sorter" ],
    [ "List", "class_list.html", "class_list" ],
    [ "ListElement", "class_list_element.html", "class_list_element" ],
    [ "ListSaver", "class_list_saver.html", "class_list_saver" ],
    [ "MergeSorter", "class_merge_sorter.html", "class_merge_sorter" ],
    [ "MyBenchmark", "class_my_benchmark.html", "class_my_benchmark" ],
    [ "MyBenchmarkObserver", "class_my_benchmark_observer.html", "class_my_benchmark_observer" ],
    [ "MyList", "class_my_list.html", "class_my_list" ],
    [ "MyListElement", "class_my_list_element.html", "class_my_list_element" ],
    [ "MyQueue", "class_my_queue.html", "class_my_queue" ],
    [ "MyStack", "class_my_stack.html", "class_my_stack" ],
    [ "NumberGenerator", "class_number_generator.html", null ],
    [ "Observable", "class_observable.html", "class_observable" ],
    [ "ObservableAVLTree", "class_observable_a_v_l_tree.html", "class_observable_a_v_l_tree" ],
    [ "ObservableHeapSorter", "class_observable_heap_sorter.html", "class_observable_heap_sorter" ],
    [ "ObservableMergeSorter", "class_observable_merge_sorter.html", "class_observable_merge_sorter" ],
    [ "ObservableQuickSorter", "class_observable_quick_sorter.html", "class_observable_quick_sorter" ],
    [ "Observer", "class_observer.html", "class_observer" ],
    [ "QuickSorter", "class_quick_sorter.html", "class_quick_sorter" ],
    [ "Sorter", "class_sorter.html", "class_sorter" ]
];